### ISSUE TITLE
Document and tidy code

### ISSUE THREAD

**Issue by 28raining** [Yaffle/Expression#10]
There isn't really any documentation. I can't figure out how to use `toLaTex()`, maybe it doesn't work?

To use this function;
`ExpressionParser.parse()`
the user must import these packages
```
import Expression from './Expression.js';
import './complex.js';
import ExpressionParser from './ExpressionParser.js';
import Polynomial from './Polynomial.js';
import './polynomial-roots-finding.js';
import './toMathML.js';
```
which is frustratingly messy. 

Seems like project was abandoned. Which is fair enough. But if you do return to it, these could be a great improvement.

**Comment by Yaffle** [comment]
I am using the project, the documentation is needed indeed

**Comment by Yaffle** [comment]
@28raining 

You can import many things from index.js. The code below works for me:

```
  import {ExpressionParser} from './node_modules/@yaffle/expression/index.js';

  // Note: toLaTeX is deprecated
  import './node_modules/@yaffle/expression/toLaTeX.js';
  console.log(ExpressionParser.parse('{{1,2},{3,4}}').toLaTeX()); // \begin{pmatrix}1 & 2 \\ 3 & 4\end{pmatrix}

```

toLaTeX.js module was abandoned, not the project :-)
I am working on the project from time to time, and using it for my personal project. The good documentation is missed, do you know how to create a good and easy to maintain documentation? 
toLaTeX.js is obsolete now, because I am not using it, instead I am doing toMathML + a script to convert MathML into LaTeX . Seems, this small conversion script is not shared now.
